name: Splunk-Detection-Sync

on:
  push:
    # Test mərhələsində 'paths' filtrini müvəqqəti bağlaya bilərsən
    # Amma qalsın deyirsənsə, mütləq splunk/ qovluğuna fayl at.
    paths:
      - 'splunk/**'

jobs:
  deploy-splunk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Splunk Deploy Script
        env:
          # Secret adını SPLUNK_URL etdim (Səndə belə idi)
          SPLUNK_URL: ${{ secrets.SPLUNK_URL }}
          SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
        run: python scripts/sync_splunk.py
